name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  NODE_VERSION: 18

jobs:

  jest_tests:
    name: Jest tests
    runs-on: [ self-hosted ]
    steps:

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci

      - name: Jest
        shell: bash
        run: npm run test
